networks:
  GDS_cluster:

services:
  core1:
    hostname: core1
    image: neo4j:4.4-enterprise
    networks:
      - GDS_cluster
    ports:
      - 7474:7474
      - 7687:7687
      - 6477:6477
    volumes:
      - ./core1/conf:/conf
      - ./core1/data:/data
      - ./core1/plugins:/plugins
      - ./core1/logs:/logs
      - ./core1/metrics:/metrics
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_listen__address=0.0.0.0:8881
      - NEO4J_dbms_routing_advertised__address=core1:8881

  core2:
    hostname: core2
    image: neo4j:4.4-enterprise
    networks:
      - GDS_cluster
    ports:
      - 7475:7475
      - 7688:7688
      - 6478:6478
    volumes:
      - ./core2/conf:/conf
      - ./core2/data:/data
      - ./core2/plugins:/plugins
      - ./core2/logs:/logs
      - ./core2/metrics:/metrics
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_listen__address=0.0.0.0:8881
      - NEO4J_dbms_routing_advertised__address=core2:8881

  core3:
    hostname: core3
    image: neo4j:4.4-enterprise
    networks:
      - GDS_cluster
    ports:
      - 7476:7476
      - 7689:7689
      - 6479:6479
    volumes:
      - ./core3/conf:/conf
      - ./core3/data:/data
      - ./core3/plugins:/plugins
      - ./core3/logs:/logs
      - ./core3/metrics:/metrics
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_bolt_listen__address=:7689
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_listen__address=0.0.0.0:8881
      - NEO4J_dbms_routing_advertised__address=core3:8881

  read-gds:
    hostname: read-gds
    image: neo4j:4.4-enterprise
    networks:
      - GDS_cluster
    ports:
      - 7477:7477
      - 7690:7690
      - 6480:6480
    volumes:
      - ./read-gds/conf:/conf
      - ./read-gds/data:/data
      - ./read-gds/plugins:/plugins
      - ./read-gds/logs:/logs
      - ./read-gds/metrics:/metrics
      - ./read-gds/license:/license
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7477
      - NEO4J_dbms_connector_bolt_listen__address=:7690
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_gds_enterprise_license__file=/license/gds.license